/*

  Problem 2: Even Fibonacci Numbers

  Each new term in the Fibonacci sequence is generated by adding the previous 
  two terms. By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed
  four million, find the sum of the even-valued terms.

*/

const {
  generators: { fibonacciNumbers },
} = require("./utils");

function solve() {
  let sum = 0;

  for (const Fn of fibonacciNumbers()) {
    if (Fn > 4_000_000) {
      break;
    }

    if (Fn % 2 === 0) {
      sum += Fn;
    }
  }

  return sum;
}

exports.solve = solve;
